%-----------------------------------------------------------------------
% Job saved on 10-Jun-2018 14:39:38 by cfg_util (rev $Rev: 6942 $)
% spm SPM - SPM12 (7219)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
matlabbatch{1}.spm.stats.factorial_design.dir = {'/data/nimble/work/katebray/data/FACTS_T2/CAT12/VBM_customised_for_pediatric/6_Stats/Multiple_regression_models/Cog_emp'};
%%
matlabbatch{1}.spm.stats.factorial_design.des.mreg.scans = {
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.100/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.101/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.102/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.104/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.105/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.108/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.109/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.110/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.111/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.113/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.114/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.115/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.116/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.117/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.118/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.119/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.120/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.121/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.122/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.124/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.125/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.126/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.127/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.128/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.129/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.13/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.130/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.131/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.133/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.134/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.136/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.137/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.138/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.139/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.14/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.140/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.141/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.143/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.145/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.146/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.147/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.148/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.149/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.15/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.151/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.152/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.153/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.154/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.155/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.156/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.157/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.16/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.160/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.164/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.165/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.17/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.18/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.20/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.21/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.22/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.23/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.25/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.26/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.27/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.28/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.29/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.3/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.30/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.31/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.34/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.35/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.36/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.37/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.38/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.39/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.4/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.40/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.41/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.44/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.45/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.46/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.47/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.50/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.51/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.52/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.53/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.54/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.55/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.57/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.58/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.59/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.61/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.62/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.63/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.65/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.67/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.68/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.69/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.7/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.70/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.71/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.73/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.74/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.75/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.76/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.77/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.78/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.8/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.81/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.82/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.83/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.84/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.85/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.86/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.87/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.88/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.89/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.9/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.90/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.91/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.92/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.95/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.96/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.97/t1/mri/smwp10001.nii,1'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.99/t1/mri/smwp10001.nii,1'
                                                            };
%%
%%
matlabbatch{1}.spm.stats.factorial_design.des.mreg.mcov(1).c = [17
10
12
12
18
14
17
13
11
16
14
16
16
11
11
16
16
8
12
13
16
20
18
12
9
12
11
16
12
13
17
8
14
18
15
4
15
15
15
17
18
13
13
16
11
17
13
15
15
17
17
12
18
13
17
14
14
16
13
12
13
14
12
12
15
15
8
17
10
15
14
17
14
19
10
10
15
16
10
13
12
15
10
10
10
12
14
12
16
13
12
13
12
12
12
12
14
13
13
18
8
9
15
12
13
13
10
9
11
16
12
12
8
14
14
16
11
14
19
10
13
15
16
14
13];
%%
matlabbatch{1}.spm.stats.factorial_design.des.mreg.mcov(1).cname = 'cognitive_empathy';
matlabbatch{1}.spm.stats.factorial_design.des.mreg.mcov(1).iCC = 1;
%%
matlabbatch{1}.spm.stats.factorial_design.des.mreg.mcov(2).c = [114.12
                                                                124.11
                                                                120.03
                                                                114.15
                                                                119.41
                                                                124.47
                                                                116.75
                                                                114.61
                                                                114.81
                                                                117.8
                                                                116.48
                                                                115.4
                                                                116.55
                                                                124.77
                                                                120.13
                                                                125.59
                                                                119.38
                                                                115.3
                                                                120.89
                                                                117.04
                                                                122.33
                                                                124.87
                                                                116.45
                                                                114.41
                                                                119.15
                                                                127.86
                                                                116.91
                                                                114.12
                                                                115.46
                                                                122.53
                                                                120.16
                                                                116.32
                                                                121.25
                                                                114.31
                                                                122.5
                                                                116.25
                                                                115.1
                                                                119.93
                                                                122.53
                                                                124.64
                                                                122.14
                                                                125.46
                                                                129.93
                                                                118.78
                                                                127.89
                                                                122.17
                                                                124.77
                                                                115.3
                                                                126.9
                                                                119.97
                                                                127.23
                                                                118.29
                                                                118.98
                                                                126.21
                                                                126.67
                                                                114.9
                                                                116.78
                                                                124.57
                                                                120.26
                                                                118.85
                                                                117.99
                                                                114.02
                                                                121.51
                                                                122.4
                                                                118.36
                                                                127.89
                                                                116.84
                                                                115.82
                                                                117.83
                                                                129.17
                                                                114.81
                                                                116.84
                                                                115.27
                                                                126.64
                                                                116.88
                                                                122.24
                                                                120.16
                                                                120.49
                                                                118.32
                                                                120.72
                                                                126.48
                                                                114.44
                                                                115.63
                                                                122.93
                                                                117.27
                                                                125.06
                                                                117.9
                                                                124.67
                                                                122.73
                                                                116.94
                                                                117.04
                                                                122.83
                                                                124.08
                                                                120.3
                                                                121.18
                                                                122.86
                                                                118.85
                                                                122.1
                                                                125.62
                                                                113.03
                                                                113.36
                                                                113.72
                                                                123.22
                                                                118.85
                                                                115.04
                                                                120.95
                                                                122.6
                                                                113.59
                                                                118.98
                                                                118.82
                                                                117.9
                                                                123.02
                                                                120.2
                                                                121.38
                                                                123.91
                                                                124.47
                                                                113.95
                                                                124.27
                                                                115.04
                                                                115.92
                                                                126.74
                                                                115.86
                                                                117.53
                                                                113.82
                                                                114.51];
%%
matlabbatch{1}.spm.stats.factorial_design.des.mreg.mcov(2).cname = 'Age';
matlabbatch{1}.spm.stats.factorial_design.des.mreg.mcov(2).iCC = 1;
%%
matlabbatch{1}.spm.stats.factorial_design.des.mreg.mcov(3).c = [0
                                                                1
                                                                0
                                                                1
                                                                0
                                                                0
                                                                0
                                                                1
                                                                1
                                                                0
                                                                0
                                                                0
                                                                1
                                                                1
                                                                0
                                                                0
                                                                1
                                                                1
                                                                0
                                                                0
                                                                0
                                                                1
                                                                1
                                                                0
                                                                1
                                                                1
                                                                1
                                                                0
                                                                0
                                                                0
                                                                0
                                                                1
                                                                1
                                                                1
                                                                0
                                                                1
                                                                1
                                                                0
                                                                1
                                                                0
                                                                0
                                                                1
                                                                1
                                                                1
                                                                0
                                                                1
                                                                1
                                                                1
                                                                1
                                                                1
                                                                0
                                                                0
                                                                0
                                                                1
                                                                0
                                                                1
                                                                0
                                                                1
                                                                1
                                                                1
                                                                1
                                                                0
                                                                1
                                                                0
                                                                1
                                                                0
                                                                1
                                                                1
                                                                1
                                                                1
                                                                0
                                                                1
                                                                1
                                                                1
                                                                0
                                                                1
                                                                0
                                                                0
                                                                1
                                                                0
                                                                0
                                                                1
                                                                0
                                                                1
                                                                1
                                                                0
                                                                0
                                                                0
                                                                0
                                                                1
                                                                1
                                                                1
                                                                0
                                                                1
                                                                0
                                                                0
                                                                0
                                                                0
                                                                1
                                                                0
                                                                1
                                                                0
                                                                1
                                                                0
                                                                1
                                                                0
                                                                0
                                                                0
                                                                0
                                                                1
                                                                0
                                                                1
                                                                0
                                                                0
                                                                0
                                                                0
                                                                0
                                                                0
                                                                1
                                                                0
                                                                1
                                                                0
                                                                0
                                                                0
                                                                0];
%%
matlabbatch{1}.spm.stats.factorial_design.des.mreg.mcov(3).cname = 'Gender';
matlabbatch{1}.spm.stats.factorial_design.des.mreg.mcov(3).iCC = 1;
%%
matlabbatch{1}.spm.stats.factorial_design.des.mreg.mcov(4).c = [1496.76
                                                                1623.97
                                                                1434
                                                                1306.14
                                                                1469.46
                                                                1459.02
                                                                1416.17
                                                                1414.68
                                                                1557.23
                                                                1696.14
                                                                1469.27
                                                                1579.25
                                                                1559.78
                                                                1525.17
                                                                1310.96
                                                                1352.32
                                                                1514.75
                                                                1740.76
                                                                1258.08
                                                                1617.9
                                                                1305.05
                                                                1455.52
                                                                1401.54
                                                                1320.31
                                                                1497.47
                                                                1787.22
                                                                1330.15
                                                                1419.97
                                                                1189.34
                                                                1364.41
                                                                1468.1
                                                                1615.13
                                                                1742.71
                                                                1449.94
                                                                1461.76
                                                                1472.99
                                                                1636.32
                                                                1366.58
                                                                1621.4
                                                                1285.19
                                                                1417
                                                                1694.98
                                                                1525.29
                                                                1419.94
                                                                1224.96
                                                                1807.95
                                                                1434.77
                                                                1449.08
                                                                1703.97
                                                                1551.62
                                                                1413.62
                                                                1472.83
                                                                1461.97
                                                                1658.18
                                                                1390.59
                                                                1542.51
                                                                1408.62
                                                                1472.46
                                                                1231.79
                                                                1443.26
                                                                1442.87
                                                                1526.79
                                                                1319.85
                                                                1350.53
                                                                1346.57
                                                                1549.78
                                                                1606.89
                                                                1583.15
                                                                1383.08
                                                                1614.05
                                                                1468.01
                                                                1526.82
                                                                1665.03
                                                                1488.88
                                                                1271.88
                                                                1572.21
                                                                1559.13
                                                                1440.89
                                                                1556.53
                                                                1311.78
                                                                1439.79
                                                                1546.66
                                                                1269.51
                                                                1328.93
                                                                1499.33
                                                                1333.57
                                                                1234.26
                                                                1392.18
                                                                1559.05
                                                                1520.58
                                                                1341.6
                                                                1374.44
                                                                1512.6
                                                                1504.86
                                                                1401.03
                                                                1442.41
                                                                1376.35
                                                                1548.64
                                                                1421.81
                                                                1550.3
                                                                1576.19
                                                                1385.84
                                                                1630.51
                                                                1367.14
                                                                1647.49
                                                                1255.57
                                                                1264.06
                                                                1392.46
                                                                1477.17
                                                                1715.68
                                                                1624.59
                                                                1666.88
                                                                1493.08
                                                                1458.68
                                                                1184.35
                                                                1585.25
                                                                1272.41
                                                                1570.53
                                                                1548.75
                                                                1481.13
                                                                1506.46
                                                                1581.24
                                                                1465.09
                                                                1344.11
                                                                1376.27];
%%
matlabbatch{1}.spm.stats.factorial_design.des.mreg.mcov(4).cname = 'TIV';
matlabbatch{1}.spm.stats.factorial_design.des.mreg.mcov(4).iCC = 1;
matlabbatch{1}.spm.stats.factorial_design.des.mreg.incint = 1;
matlabbatch{1}.spm.stats.factorial_design.cov = struct('c', {}, 'cname', {}, 'iCFI', {}, 'iCC', {});
matlabbatch{1}.spm.stats.factorial_design.multi_cov = struct('files', {}, 'iCFI', {}, 'iCC', {});
matlabbatch{1}.spm.stats.factorial_design.masking.tm.tma.athresh = 0.1;
matlabbatch{1}.spm.stats.factorial_design.masking.im = 1;
matlabbatch{1}.spm.stats.factorial_design.masking.em = {''};
matlabbatch{1}.spm.stats.factorial_design.globalc.g_omit = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.gmsca.gmsca_no = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.glonorm = 1;
