%-----------------------------------------------------------------------
% Job saved on 14-Jun-2018 13:46:08 by cfg_util (rev $Rev: 6942 $)
% spm SPM - SPM12 (7219)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
matlabbatch{1}.spm.stats.factorial_design.dir = {'/data/nimble/work/katebray/data/FACTS_T2/CAT12/VBM_customised_for_pediatric/Surface/Stats/Emp_dist'};
%%
%Notes 110 and 143 missing emp_dist data so removed
matlabbatch{1}.spm.stats.factorial_design.des.mreg.scans = {
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.100/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.101/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.102/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.104/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.105/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.108/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.109/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.111/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.113/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.114/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.115/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.116/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.117/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.118/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.119/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.120/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.121/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.122/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.124/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.125/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.126/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.127/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.128/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.129/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.13/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.130/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.131/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.133/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.134/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.136/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.137/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.138/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.139/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.14/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.140/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.141/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.145/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.146/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.147/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.148/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.149/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.15/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.151/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.152/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.153/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.154/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.155/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.156/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.157/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.16/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.160/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.164/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.165/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.17/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.18/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.20/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.21/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.22/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.23/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.25/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.26/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.27/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.28/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.29/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.3/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.30/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.31/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.34/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.35/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.36/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.37/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.38/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.39/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.4/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.40/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.41/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.44/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.45/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.46/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.47/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.50/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.51/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.52/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.53/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.54/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.55/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.57/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.58/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.59/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.61/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.62/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.63/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.65/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.67/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.68/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.69/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.7/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.70/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.71/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.73/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.74/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.75/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.76/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.77/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.78/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.8/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.81/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.82/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.83/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.84/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.85/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.86/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.87/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.88/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.89/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.9/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.90/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.91/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.92/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.95/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.96/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.97/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            '/data/nimble/work/katebray/data/FACTS_T2/1047.2.63.99/t1/surf/s15.mesh.thickness.resampled_32k.0001.gii'
                                                            };
%%
%%
matlabbatch{1}.spm.stats.factorial_design.des.mreg.mcov(1).c = [14
                                                                6
                                                                13
                                                                7
                                                                10
                                                                7
                                                                8
                                                                5
                                                                9
                                                                4
                                                                8
                                                                7
                                                                8
                                                                11
                                                                9
                                                                9
                                                                5
                                                                6
                                                                4
                                                                6
                                                                7
                                                                3
                                                                6
                                                                6
                                                                5
                                                                10
                                                                4
                                                                11
                                                                10
                                                                13
                                                                11
                                                                7
                                                                3
                                                                6
                                                                3
                                                                9
                                                                10
                                                                18
                                                                11
                                                                10
                                                                9
                                                                3
                                                                9
                                                                12
                                                                10
                                                                6
                                                                11
                                                                7
                                                                7
                                                                9
                                                                10
                                                                9
                                                                10
                                                                8
                                                                11
                                                                13
                                                                7
                                                                9
                                                                6
                                                                8
                                                                4
                                                                10
                                                                11
                                                                9
                                                                5
                                                                4
                                                                6
                                                                13
                                                                5
                                                                6
                                                                10
                                                                9
                                                                4
                                                                7
                                                                13
                                                                13
                                                                9
                                                                10
                                                                8
                                                                4
                                                                4
                                                                3
                                                                4
                                                                12
                                                                11
                                                                5
                                                                9
                                                                11
                                                                3
                                                                5
                                                                11
                                                                13
                                                                13
                                                                11
                                                                7
                                                                12
                                                                6
                                                                3
                                                                7
                                                                8
                                                                6
                                                                11
                                                                6
                                                                5
                                                                7
                                                                9
                                                                12
                                                                13
                                                                4
                                                                9
                                                                9
                                                                11
                                                                6
                                                                15
                                                                3
                                                                6
                                                                15
                                                                8
                                                                11
                                                                9
                                                                11
                                                                8
                                                                12];
%%
matlabbatch{1}.spm.stats.factorial_design.des.mreg.mcov(1).cname = 'Empathic_distress';
matlabbatch{1}.spm.stats.factorial_design.des.mreg.mcov(1).iCC = 1;
%%
matlabbatch{1}.spm.stats.factorial_design.des.mreg.mcov(2).c = [0
                                                                1
                                                                0
                                                                1
                                                                0
                                                                0
                                                                0
                                                                1
                                                                0
                                                                0
                                                                0
                                                                1
                                                                1
                                                                0
                                                                0
                                                                1
                                                                1
                                                                0
                                                                0
                                                                0
                                                                1
                                                                1
                                                                0
                                                                1
                                                                1
                                                                1
                                                                0
                                                                0
                                                                0
                                                                0
                                                                1
                                                                1
                                                                1
                                                                0
                                                                1
                                                                1
                                                                1
                                                                0
                                                                0
                                                                1
                                                                1
                                                                1
                                                                0
                                                                1
                                                                1
                                                                1
                                                                1
                                                                1
                                                                0
                                                                0
                                                                0
                                                                1
                                                                0
                                                                1
                                                                0
                                                                1
                                                                1
                                                                1
                                                                1
                                                                0
                                                                1
                                                                0
                                                                1
                                                                0
                                                                1
                                                                1
                                                                1
                                                                1
                                                                0
                                                                1
                                                                1
                                                                1
                                                                0
                                                                1
                                                                0
                                                                0
                                                                1
                                                                0
                                                                0
                                                                1
                                                                0
                                                                1
                                                                1
                                                                0
                                                                0
                                                                0
                                                                0
                                                                1
                                                                1
                                                                1
                                                                0
                                                                1
                                                                0
                                                                0
                                                                0
                                                                0
                                                                1
                                                                0
                                                                1
                                                                0
                                                                1
                                                                0
                                                                1
                                                                0
                                                                0
                                                                0
                                                                0
                                                                1
                                                                0
                                                                1
                                                                0
                                                                0
                                                                0
                                                                0
                                                                0
                                                                0
                                                                1
                                                                0
                                                                1
                                                                0
                                                                0
                                                                0
                                                                0];
%%
matlabbatch{1}.spm.stats.factorial_design.des.mreg.mcov(2).cname = 'Gender';
matlabbatch{1}.spm.stats.factorial_design.des.mreg.mcov(2).iCC = 1;
%%
matlabbatch{1}.spm.stats.factorial_design.des.mreg.mcov(3).c = [114.12
                                                                124.11
                                                                120.03
                                                                114.15
                                                                119.41
                                                                124.47
                                                                116.75
                                                                114.81
                                                                117.8
                                                                116.48
                                                                115.4
                                                                116.55
                                                                124.77
                                                                120.13
                                                                125.59
                                                                119.38
                                                                115.3
                                                                120.89
                                                                117.04
                                                                122.33
                                                                124.87
                                                                116.45
                                                                114.41
                                                                119.15
                                                                127.86
                                                                116.91
                                                                114.12
                                                                115.46
                                                                122.53
                                                                120.16
                                                                116.32
                                                                121.25
                                                                114.31
                                                                122.5
                                                                116.25
                                                                115.1
                                                                122.53
                                                                124.64
                                                                122.14
                                                                125.46
                                                                129.93
                                                                118.78
                                                                127.89
                                                                122.17
                                                                124.77
                                                                115.3
                                                                126.9
                                                                119.97
                                                                127.23
                                                                118.29
                                                                118.98
                                                                126.21
                                                                126.67
                                                                114.9
                                                                116.78
                                                                124.57
                                                                120.26
                                                                118.85
                                                                117.99
                                                                114.02
                                                                121.51
                                                                122.4
                                                                118.36
                                                                127.89
                                                                116.84
                                                                115.82
                                                                117.83
                                                                129.17
                                                                114.81
                                                                116.84
                                                                115.27
                                                                126.64
                                                                116.88
                                                                122.24
                                                                120.16
                                                                120.49
                                                                118.32
                                                                120.72
                                                                126.48
                                                                114.44
                                                                115.63
                                                                122.93
                                                                117.27
                                                                125.06
                                                                117.9
                                                                124.67
                                                                122.73
                                                                116.94
                                                                117.04
                                                                122.83
                                                                124.08
                                                                120.3
                                                                121.18
                                                                122.86
                                                                118.85
                                                                122.1
                                                                125.62
                                                                113.03
                                                                113.36
                                                                113.72
                                                                123.22
                                                                118.85
                                                                115.04
                                                                120.95
                                                                122.6
                                                                113.59
                                                                118.98
                                                                118.82
                                                                117.9
                                                                123.02
                                                                120.2
                                                                121.38
                                                                123.91
                                                                124.47
                                                                113.95
                                                                124.27
                                                                115.04
                                                                115.92
                                                                126.74
                                                                115.86
                                                                117.53
                                                                113.82
                                                                114.51];
%%
matlabbatch{1}.spm.stats.factorial_design.des.mreg.mcov(3).cname = 'Age';
matlabbatch{1}.spm.stats.factorial_design.des.mreg.mcov(3).iCC = 1;
matlabbatch{1}.spm.stats.factorial_design.des.mreg.incint = 1;
matlabbatch{1}.spm.stats.factorial_design.cov = struct('c', {}, 'cname', {}, 'iCFI', {}, 'iCC', {});
matlabbatch{1}.spm.stats.factorial_design.multi_cov = struct('files', {}, 'iCFI', {}, 'iCC', {});
matlabbatch{1}.spm.stats.factorial_design.masking.tm.tm_none = 1;
matlabbatch{1}.spm.stats.factorial_design.masking.im = 1;
matlabbatch{1}.spm.stats.factorial_design.masking.em = {''};
matlabbatch{1}.spm.stats.factorial_design.globalc.g_omit = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.gmsca.gmsca_no = 1;
matlabbatch{1}.spm.stats.factorial_design.globalm.glonorm = 1;
matlabbatch{2}.spm.tools.cat.tools.check_SPM.spmmat(1) = cfg_dep('Factorial design specification: SPM.mat File', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
matlabbatch{2}.spm.tools.cat.tools.check_SPM.check_SPM_cov.do_check_cov.use_unsmoothed_data = 1;
matlabbatch{2}.spm.tools.cat.tools.check_SPM.check_SPM_cov.do_check_cov.adjust_data = 1;
matlabbatch{2}.spm.tools.cat.tools.check_SPM.check_SPM_ortho = 1;
